### ISSUE TITLE
Crashing while booting in verbose mode

### ISSUE THREAD

**Issue by Warmachine28** [SiddheshNan/Acer-A515-51G-Hackintosh#1]
I followed all the instructions from README.md but as soon I configure config file and restarts, it crashes while booting and doesn't boot

**Comment by SiddheshNan** [comment]
@Warmachine28 
Hey,
Are you booting with verbose mode? if yes then please upload the screenshot here.
Also firstly you have to disable secure boot on this laptop( I forgot to mention this on readme)
Use F2 key after ACER logo to get into BIOS mode, then you'll have to add admin password(something like 1234) after that you will be able to disable secure boot, because clover doesn't work with secure boot, also while you're at it change touchpad to BASIC from MULTI-TOUCH. & Reboot.

**Comment by Warmachine28** [comment]
It booted idk how but trackpad and keyboard is broke

**Comment by Warmachine28** [comment]
I already did everything necessary in bios because I was tryinghttps://github.com/h-okon/Acer-Aspire-A515-Hackintosh . There also the keyboard is broke. You can check the issue tab on h-okon repo

**Comment by Warmachine28** [comment]
Checking in kextstat VoodooPS2Controller and its modules not loading on boot at all.

**Comment by SiddheshNan** [comment]
is touch-pad set to multi-touch? I tried to reproduce the problem and it seems that keyboard is also not working in my case if touch-pad is set to multi-touch, you should try changing it to basic.

**Comment by Warmachine28** [comment]
Then both will work or what??

**Comment by SiddheshNan** [comment]
You should check and see what works best for your system, you can change it back if you don't want to.

**Comment by Warmachine28** [comment]
Did clean flash with ur clover configs. I also did setup SMbois But it's getting kernel panics
[verbose-1.zip](https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh/files/3327014/verbose-1.zip)
